version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "discovery.type=single-node"      
      - "cluster.routing.allocation.disk.watermark.low=2gb"
      - "cluster.routing.allocation.disk.watermark.high=1gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=500mb"
    ports:
      - "9200:9200"
  
  app:
    image: "dainst/argos:latest"
    container_name: "argos-app"
    ports: 
      - "80:4001"
    volumes: 
      - "./priv/elasticsearch-mapping.json:/elasticsearch-mapping.json"
