version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "discovery.type=single-node"      
      - "cluster.routing.allocation.disk.watermark.low=2gb"
      - "cluster.routing.allocation.disk.watermark.high=1gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=500mb"
  
  api:
    image: "dainst/argos_api:latest"
    container_name: "argos-api"
    volumes: 
      - "/opt/argos/elasticsearch-mapping.json:/elasticsearch-mapping.json"
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:api.test.idai.world"
        - "traefik.port=4001"
  
  aggregation:
    image: "dainst/argos_aggregation:latest"
    container_name: "argos-aggregation"
  
  traefik:
    image: "traefik:v2.4"
    container_name: "argos-traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/traefik/acme.json:/acme.json"
      - "/opt/traefik/traefik.toml:/etc/traefik/traefik.toml"

  