version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
